/**
 * Typed client for the Oz API.
 *
 * @example
 * ```ts
 * import { createOzClient } from "@tanko/oz-client";
 *
 * const client = createOzClient({ baseUrl: "https://api.example.com" });
 * const response = await client.patients.list();
 * ```
 *
 * This file was generated by cargo xtask build-client. Do not edit directly.
 */

import createClient, {
  type Client,
  type ClientForPath,
  type ClientOptions,
  type FetchOptions,
  type Middleware,
} from "openapi-fetch";
import type { components, operations, paths } from "./codegen.d.ts";

/** OpenAPI path, operation, and component definitions for the Oz API. */
export type { components, operations, paths };

/** Request lifecycle callbacks applied to every request unless overridden. */
export type OzClientCallbacks = {
  /** Runs before the request is sent. */
  onRequest?: Middleware["onRequest"];
  /** Runs after a response is received. */
  onResponse?: Middleware["onResponse"];
  /** Runs when the request fails. */
  onError?: Middleware["onError"];
};

/** Options used to construct an Oz client. */
export type OzClientOptions = ClientOptions &
  OzClientCallbacks & {
    baseUrl: string;
  };

/** Request options accepted by a generated endpoint method. */
export type OzRequestOptions<Operation> = FetchOptions<Operation> & OzClientCallbacks;

function withCallbacks<Operation>(
  body: OzRequestOptions<Operation> | undefined,
  defaults: OzClientCallbacks,
): FetchOptions<Operation> {
  const {
    onRequest,
    onResponse,
    onError,
    middleware: requestMiddleware,
    ...request
  } = body ?? {};
  const callbacks = {
    onRequest: onRequest ?? defaults.onRequest,
    onResponse: onResponse ?? defaults.onResponse,
    onError: onError ?? defaults.onError,
  };
  const hasCallbacks = Object.values(callbacks).some(Boolean);

  return {
    ...request,
    middleware: [
      ...(requestMiddleware ?? []),
      ...(hasCallbacks ? [callbacks] : []),
    ],
  } as FetchOptions<Operation>;
}

/** OpenAPI schema `ActiveTreatment`. */
export type ActiveTreatment = components["schemas"]["ActiveTreatment"];
/** OpenAPI schema `Appointment`. */
export type Appointment = components["schemas"]["Appointment"];
/** OpenAPI schema `AppointmentId`. */
export type AppointmentId = components["schemas"]["AppointmentId"];
/** OpenAPI schema `AuthToken`. */
export type AuthToken = components["schemas"]["AuthToken"];
/** OpenAPI schema `BillingType`. */
export type BillingType = components["schemas"]["BillingType"];
/** OpenAPI schema `ChangePasswordRequest`. */
export type ChangePasswordRequest = components["schemas"]["ChangePasswordRequest"];
/** OpenAPI schema `ClinicHistoryResponse`. */
export type ClinicHistoryResponse = components["schemas"]["ClinicHistoryResponse"];
/** OpenAPI schema `ClinicStats`. */
export type ClinicStats = components["schemas"]["ClinicStats"];
/** OpenAPI schema `CreateClinicRequest`. */
export type CreateClinicRequest = components["schemas"]["CreateClinicRequest"];
/** OpenAPI schema `CreateClinicResponse`. */
export type CreateClinicResponse = components["schemas"]["CreateClinicResponse"];
/** OpenAPI schema `CreateNoteRequest`. */
export type CreateNoteRequest = components["schemas"]["CreateNoteRequest"];
/** OpenAPI schema `CreateObraSocialRequest`. */
export type CreateObraSocialRequest = components["schemas"]["CreateObraSocialRequest"];
/** OpenAPI schema `CreatePatientRequest`. */
export type CreatePatientRequest = components["schemas"]["CreatePatientRequest"];
/** OpenAPI schema `CreatePaymentRequest`. */
export type CreatePaymentRequest = components["schemas"]["CreatePaymentRequest"];
/** OpenAPI schema `CreateRequest`. */
export type CreateRequest = components["schemas"]["CreateRequest"];
/** OpenAPI schema `CreateServiceRequest`. */
export type CreateServiceRequest = components["schemas"]["CreateServiceRequest"];
/** OpenAPI schema `CreateSessionRequest`. */
export type CreateSessionRequest = components["schemas"]["CreateSessionRequest"];
/** OpenAPI schema `CreateTreatmentRequest`. */
export type CreateTreatmentRequest = components["schemas"]["CreateTreatmentRequest"];
/** OpenAPI schema `CreateUserRequest`. */
export type CreateUserRequest = components["schemas"]["CreateUserRequest"];
/** OpenAPI schema `Credentials`. */
export type Credentials = components["schemas"]["Credentials"];
/** OpenAPI schema `Date`. */
export type Date = components["schemas"]["Date"];
/** OpenAPI schema `DeletePaymentRequest`. */
export type DeletePaymentRequest = components["schemas"]["DeletePaymentRequest"];
/** OpenAPI schema `ErrorCode`. */
export type ErrorCode = components["schemas"]["ErrorCode"];
/** OpenAPI schema `ErrorResponse`. */
export type ErrorResponse = components["schemas"]["ErrorResponse"];
/** OpenAPI schema `ForgotPasswordRequest`. */
export type ForgotPasswordRequest = components["schemas"]["ForgotPasswordRequest"];
/** OpenAPI schema `LoginResponse`. */
export type LoginResponse = components["schemas"]["LoginResponse"];
/** OpenAPI schema `NoteResponse`. */
export type NoteResponse = components["schemas"]["NoteResponse"];
/** OpenAPI schema `ObraSocialResponse`. */
export type ObraSocialResponse = components["schemas"]["ObraSocialResponse"];
/** OpenAPI schema `PatientData`. */
export type PatientData = components["schemas"]["PatientData"];
/** OpenAPI schema `PatientId`. */
export type PatientId = components["schemas"]["PatientId"];
/** OpenAPI schema `PatientResponse`. */
export type PatientResponse = components["schemas"]["PatientResponse"];
/** OpenAPI schema `PatientStatus`. */
export type PatientStatus = components["schemas"]["PatientStatus"];
/** OpenAPI schema `PaymentDetail`. */
export type PaymentDetail = components["schemas"]["PaymentDetail"];
/** OpenAPI schema `PaymentMethod`. */
export type PaymentMethod = components["schemas"]["PaymentMethod"];
/** OpenAPI schema `PaymentResponse`. */
export type PaymentResponse = components["schemas"]["PaymentResponse"];
/** OpenAPI schema `RoleData`. */
export type RoleData = components["schemas"]["RoleData"];
/** OpenAPI schema `ServiceResponse`. */
export type ServiceResponse = components["schemas"]["ServiceResponse"];
/** OpenAPI schema `SessionId`. */
export type SessionId = components["schemas"]["SessionId"];
/** OpenAPI schema `SessionResponse`. */
export type SessionResponse = components["schemas"]["SessionResponse"];
/** OpenAPI schema `SessionStatus`. */
export type SessionStatus = components["schemas"]["SessionStatus"];
/** OpenAPI schema `Staff`. */
export type Staff = components["schemas"]["Staff"];
/** OpenAPI schema `StaffId`. */
export type StaffId = components["schemas"]["StaffId"];
/** OpenAPI schema `StaffInfo`. */
export type StaffInfo = components["schemas"]["StaffInfo"];
/** OpenAPI schema `Status`. */
export type Status = components["schemas"]["Status"];
/** OpenAPI schema `Treatment`. */
export type Treatment = components["schemas"]["Treatment"];
/** OpenAPI schema `TreatmentStatus`. */
export type TreatmentStatus = components["schemas"]["TreatmentStatus"];
/** OpenAPI schema `UpdateAppointment`. */
export type UpdateAppointment = components["schemas"]["UpdateAppointment"];
/** OpenAPI schema `UpdateNoteRequest`. */
export type UpdateNoteRequest = components["schemas"]["UpdateNoteRequest"];
/** OpenAPI schema `UpdateObraSocialRequest`. */
export type UpdateObraSocialRequest = components["schemas"]["UpdateObraSocialRequest"];
/** OpenAPI schema `UpdatePatientRequest`. */
export type UpdatePatientRequest = components["schemas"]["UpdatePatientRequest"];
/** OpenAPI schema `UpdatePaymentRequest`. */
export type UpdatePaymentRequest = components["schemas"]["UpdatePaymentRequest"];
/** OpenAPI schema `UpdateServiceRequest`. */
export type UpdateServiceRequest = components["schemas"]["UpdateServiceRequest"];
/** OpenAPI schema `UpdateSessionRequest`. */
export type UpdateSessionRequest = components["schemas"]["UpdateSessionRequest"];
/** OpenAPI schema `UpdateStaffRequest`. */
export type UpdateStaffRequest = components["schemas"]["UpdateStaffRequest"];
/** OpenAPI schema `UpdateTreatmentRequest`. */
export type UpdateTreatmentRequest = components["schemas"]["UpdateTreatmentRequest"];
/** OpenAPI schema `UpdateUserSettings`. */
export type UpdateUserSettings = components["schemas"]["UpdateUserSettings"];
/** OpenAPI schema `User`. */
export type User = components["schemas"]["User"];
/** OpenAPI schema `UserId`. */
export type UserId = components["schemas"]["UserId"];
/** OpenAPI schema `UserRole`. */
export type UserRole = components["schemas"]["UserRole"];
/** OpenAPI schema `UserSettings`. */
export type UserSettings = components["schemas"]["UserSettings"];

/** The grouped, typed client returned by `createOzClient`. */
export interface OzClient {
  /** The underlying openapi-fetch client for direct path-based calls. */
  raw_client: Client<paths>;
  appointment: {
    /** Calls GET /api/v1/appointment. Per-call lifecycle callbacks override the client defaults. */
    getAllAppointmentsInTimeRange: (body: OzRequestOptions<operations["get_all_appointments_in_time_range"]>) => ReturnType<ClientForPath<paths["/api/v1/appointment"], "application/json">["GET"]>;
    /** Calls GET /api/v1/appointment/attending/{staff_id}. Per-call lifecycle callbacks override the client defaults. */
    getAllAppointmentsFromStaff: (body: OzRequestOptions<operations["get_all_appointments_from_staff"]>) => ReturnType<ClientForPath<paths["/api/v1/appointment/attending/{staff_id}"], "application/json">["GET"]>;
    /** Calls GET /api/v1/appointment/creator/{staff_id}. Per-call lifecycle callbacks override the client defaults. */
    getAllAppointmentsFromCreator: (body: OzRequestOptions<operations["get_all_appointments_from_creator"]>) => ReturnType<ClientForPath<paths["/api/v1/appointment/creator/{staff_id}"], "application/json">["GET"]>;
    /** Calls PATCH /api/v1/appointment/{appointment_id}. Per-call lifecycle callbacks override the client defaults. */
    updateAppointment: (body: OzRequestOptions<operations["update_appointment"]>) => ReturnType<ClientForPath<paths["/api/v1/appointment/{appointment_id}"], "application/json">["PATCH"]>;
  };
  auth: {
    /** Calls POST /api/v1/auth/change-password. Per-call lifecycle callbacks override the client defaults. */
    changePassword: (body: OzRequestOptions<operations["changePassword"]>) => ReturnType<ClientForPath<paths["/api/v1/auth/change-password"], "application/json">["POST"]>;
    /** Calls POST /api/v1/auth/forgot-password. Per-call lifecycle callbacks override the client defaults. */
    forgotPassword: (body: OzRequestOptions<operations["forgot_password"]>) => ReturnType<ClientForPath<paths["/api/v1/auth/forgot-password"], "application/json">["POST"]>;
    /** Calls POST /api/v1/auth/login. Per-call lifecycle callbacks override the client defaults. */
    login: (body: OzRequestOptions<operations["login"]>) => ReturnType<ClientForPath<paths["/api/v1/auth/login"], "application/json">["POST"]>;
    /** Calls POST /api/v1/auth/logout. Per-call lifecycle callbacks override the client defaults. */
    logout: (body?: OzRequestOptions<operations["logout"]>) => ReturnType<ClientForPath<paths["/api/v1/auth/logout"], "application/json">["POST"]>;
    /** Calls GET /api/v1/auth/me. Per-call lifecycle callbacks override the client defaults. */
    me: (body?: OzRequestOptions<operations["me"]>) => ReturnType<ClientForPath<paths["/api/v1/auth/me"], "application/json">["GET"]>;
    /** Calls GET /api/v1/auth/settings. Per-call lifecycle callbacks override the client defaults. */
    getUserSettings: (body?: OzRequestOptions<operations["get_user_settings"]>) => ReturnType<ClientForPath<paths["/api/v1/auth/settings"], "application/json">["GET"]>;
    /** Calls PATCH /api/v1/auth/settings. Per-call lifecycle callbacks override the client defaults. */
    updateUserSettings: (body: OzRequestOptions<operations["update_user_settings"]>) => ReturnType<ClientForPath<paths["/api/v1/auth/settings"], "application/json">["PATCH"]>;
  };
  clinic: {
    /** Calls GET /api/v1/clinic. Per-call lifecycle callbacks override the client defaults. */
    getAllClinics: (body?: OzRequestOptions<operations["get_all_clinics"]>) => ReturnType<ClientForPath<paths["/api/v1/clinic"], "application/json">["GET"]>;
    /** Calls POST /api/v1/clinic. Per-call lifecycle callbacks override the client defaults. */
    createClinic: (body: OzRequestOptions<operations["create_clinic"]>) => ReturnType<ClientForPath<paths["/api/v1/clinic"], "application/json">["POST"]>;
  };
  clinic_service: {
    /** Calls GET /api/v1/clinic_service. Per-call lifecycle callbacks override the client defaults. */
    getAllClinicServices: (body?: OzRequestOptions<operations["get_all_clinic_services"]>) => ReturnType<ClientForPath<paths["/api/v1/clinic_service"], "application/json">["GET"]>;
    /** Calls POST /api/v1/clinic_service. Per-call lifecycle callbacks override the client defaults. */
    createClinicService: (body: OzRequestOptions<operations["create_clinic_service"]>) => ReturnType<ClientForPath<paths["/api/v1/clinic_service"], "application/json">["POST"]>;
    /** Calls DELETE /api/v1/clinic_service/{service_id}. Per-call lifecycle callbacks override the client defaults. */
    deleteClinicService: (body: OzRequestOptions<operations["delete_clinic_service"]>) => ReturnType<ClientForPath<paths["/api/v1/clinic_service/{service_id}"], "application/json">["DELETE"]>;
    /** Calls GET /api/v1/clinic_service/{service_id}. Per-call lifecycle callbacks override the client defaults. */
    getClinicService: (body: OzRequestOptions<operations["get_clinic_service"]>) => ReturnType<ClientForPath<paths["/api/v1/clinic_service/{service_id}"], "application/json">["GET"]>;
    /** Calls PATCH /api/v1/clinic_service/{service_id}. Per-call lifecycle callbacks override the client defaults. */
    updateClinicService: (body: OzRequestOptions<operations["update_clinic_service"]>) => ReturnType<ClientForPath<paths["/api/v1/clinic_service/{service_id}"], "application/json">["PATCH"]>;
  };
  note: {
    /** Calls DELETE /api/v1/note/{note_id}. Per-call lifecycle callbacks override the client defaults. */
    deleteById: (body: OzRequestOptions<operations["delete_note"]>) => ReturnType<ClientForPath<paths["/api/v1/note/{note_id}"], "application/json">["DELETE"]>;
    /** Calls GET /api/v1/note/{note_id}. Per-call lifecycle callbacks override the client defaults. */
    getById: (body: OzRequestOptions<operations["get_note"]>) => ReturnType<ClientForPath<paths["/api/v1/note/{note_id}"], "application/json">["GET"]>;
    /** Calls PATCH /api/v1/note/{note_id}. Per-call lifecycle callbacks override the client defaults. */
    updateNote: (body: OzRequestOptions<operations["update_note"]>) => ReturnType<ClientForPath<paths["/api/v1/note/{note_id}"], "application/json">["PATCH"]>;
  };
  obra: {
    /** Calls GET /api/v1/obra. Per-call lifecycle callbacks override the client defaults. */
    getAllObrasSociales: (body?: OzRequestOptions<operations["get_all_obras_sociales"]>) => ReturnType<ClientForPath<paths["/api/v1/obra"], "application/json">["GET"]>;
    /** Calls POST /api/v1/obra. Per-call lifecycle callbacks override the client defaults. */
    createObraSocial: (body: OzRequestOptions<operations["create_obra_social"]>) => ReturnType<ClientForPath<paths["/api/v1/obra"], "application/json">["POST"]>;
    /** Calls GET /api/v1/obra/{name}. Per-call lifecycle callbacks override the client defaults. */
    getObraSocial: (body: OzRequestOptions<operations["get_obra_social"]>) => ReturnType<ClientForPath<paths["/api/v1/obra/{name}"], "application/json">["GET"]>;
    /** Calls PATCH /api/v1/obra/{name}. Per-call lifecycle callbacks override the client defaults. */
    updateObraSocial: (body: OzRequestOptions<operations["update_obra_social"]>) => ReturnType<ClientForPath<paths["/api/v1/obra/{name}"], "application/json">["PATCH"]>;
  };
  patient: {
    /** Calls GET /api/v1/patient. Per-call lifecycle callbacks override the client defaults. */
    getAllPatients: (body?: OzRequestOptions<operations["get_all_patients"]>) => ReturnType<ClientForPath<paths["/api/v1/patient"], "application/json">["GET"]>;
    /** Calls POST /api/v1/patient. Per-call lifecycle callbacks override the client defaults. */
    createPatient: (body: OzRequestOptions<operations["create_patient"]>) => ReturnType<ClientForPath<paths["/api/v1/patient"], "application/json">["POST"]>;
    /** Calls GET /api/v1/patient/{patient_id}. Per-call lifecycle callbacks override the client defaults. */
    getById: (body: OzRequestOptions<operations["get_patient"]>) => ReturnType<ClientForPath<paths["/api/v1/patient/{patient_id}"], "application/json">["GET"]>;
    /** Calls PATCH /api/v1/patient/{patient_id}. Per-call lifecycle callbacks override the client defaults. */
    updatePatient: (body: OzRequestOptions<operations["update_patient"]>) => ReturnType<ClientForPath<paths["/api/v1/patient/{patient_id}"], "application/json">["PATCH"]>;
    /** Calls GET /api/v1/patient/{patient_id}/clinical-history. Per-call lifecycle callbacks override the client defaults. */
    buildClinicHistory: (body: OzRequestOptions<operations["build_clinic_history"]>) => ReturnType<ClientForPath<paths["/api/v1/patient/{patient_id}/clinical-history"], "application/json">["GET"]>;
    /** Calls PATCH /api/v1/patient/{patient_id}/discharge. Per-call lifecycle callbacks override the client defaults. */
    dischargePatient: (body: OzRequestOptions<operations["discharge_patient"]>) => ReturnType<ClientForPath<paths["/api/v1/patient/{patient_id}/discharge"], "application/json">["PATCH"]>;
  };
  payment: {
    /** Calls GET /api/v1/payment. Per-call lifecycle callbacks override the client defaults. */
    getAllPayments: (body?: OzRequestOptions<operations["get_all_payments"]>) => ReturnType<ClientForPath<paths["/api/v1/payment"], "application/json">["GET"]>;
    /** Calls POST /api/v1/payment. Per-call lifecycle callbacks override the client defaults. */
    registerPayment: (body: OzRequestOptions<operations["register_payment"]>) => ReturnType<ClientForPath<paths["/api/v1/payment"], "application/json">["POST"]>;
    /** Calls GET /api/v1/payment/by-payer/{payer_id}. Per-call lifecycle callbacks override the client defaults. */
    getAllPaymentsFromId: (body: OzRequestOptions<operations["get_all_payments_from_id"]>) => ReturnType<ClientForPath<paths["/api/v1/payment/by-payer/{payer_id}"], "application/json">["GET"]>;
    /** Calls DELETE /api/v1/payment/{payment_id}. Per-call lifecycle callbacks override the client defaults. */
    deleteById: (body: OzRequestOptions<operations["delete_payment"]>) => ReturnType<ClientForPath<paths["/api/v1/payment/{payment_id}"], "application/json">["DELETE"]>;
    /** Calls GET /api/v1/payment/{payment_id}. Per-call lifecycle callbacks override the client defaults. */
    getById: (body: OzRequestOptions<operations["get_payment"]>) => ReturnType<ClientForPath<paths["/api/v1/payment/{payment_id}"], "application/json">["GET"]>;
    /** Calls PATCH /api/v1/payment/{payment_id}. Per-call lifecycle callbacks override the client defaults. */
    updatePayment: (body: OzRequestOptions<operations["update_payment"]>) => ReturnType<ClientForPath<paths["/api/v1/payment/{payment_id}"], "application/json">["PATCH"]>;
  };
  session: {
    /** Calls POST /api/v1/session. Per-call lifecycle callbacks override the client defaults. */
    createSession: (body: OzRequestOptions<operations["create_session"]>) => ReturnType<ClientForPath<paths["/api/v1/session"], "application/json">["POST"]>;
    /** Calls GET /api/v1/session/{session_id}. Per-call lifecycle callbacks override the client defaults. */
    getById: (body: OzRequestOptions<operations["get_session"]>) => ReturnType<ClientForPath<paths["/api/v1/session/{session_id}"], "application/json">["GET"]>;
    /** Calls PATCH /api/v1/session/{session_id}. Per-call lifecycle callbacks override the client defaults. */
    updateSession: (body: OzRequestOptions<operations["update_session"]>) => ReturnType<ClientForPath<paths["/api/v1/session/{session_id}"], "application/json">["PATCH"]>;
  };
  sessions: {
    /** Calls POST /api/v1/sessions/{session_id}/appointment. Per-call lifecycle callbacks override the client defaults. */
    createAppointment: (body: OzRequestOptions<operations["create_appointment"]>) => ReturnType<ClientForPath<paths["/api/v1/sessions/{session_id}/appointment"], "application/json">["POST"]>;
  };
  staff: {
    /** Calls GET /api/v1/staff. Per-call lifecycle callbacks override the client defaults. */
    getAllStaff: (body?: OzRequestOptions<operations["get_all_staff"]>) => ReturnType<ClientForPath<paths["/api/v1/staff"], "application/json">["GET"]>;
    /** Calls GET /api/v1/staff/{staff_id}. Per-call lifecycle callbacks override the client defaults. */
    getById: (body: OzRequestOptions<operations["get_staff"]>) => ReturnType<ClientForPath<paths["/api/v1/staff/{staff_id}"], "application/json">["GET"]>;
    /** Calls PATCH /api/v1/staff/{staff_id}. Per-call lifecycle callbacks override the client defaults. */
    updateStaff: (body: OzRequestOptions<operations["update_staff"]>) => ReturnType<ClientForPath<paths["/api/v1/staff/{staff_id}"], "application/json">["PATCH"]>;
  };
  treatment: {
    /** Calls POST /api/v1/treatment. Per-call lifecycle callbacks override the client defaults. */
    createTreatment: (body: OzRequestOptions<operations["create_treatment"]>) => ReturnType<ClientForPath<paths["/api/v1/treatment"], "application/json">["POST"]>;
    /** Calls GET /api/v1/treatment/patient/{patient_id}. Per-call lifecycle callbacks override the client defaults. */
    getAllTreatmentsFromPatient: (body: OzRequestOptions<operations["get_all_treatments_from_patient"]>) => ReturnType<ClientForPath<paths["/api/v1/treatment/patient/{patient_id}"], "application/json">["GET"]>;
    /** Calls GET /api/v1/treatment/staff/{staff_id}. Per-call lifecycle callbacks override the client defaults. */
    getAllTreatmentsFromStaff: (body: OzRequestOptions<operations["get_all_treatments_from_staff"]>) => ReturnType<ClientForPath<paths["/api/v1/treatment/staff/{staff_id}"], "application/json">["GET"]>;
    /** Calls DELETE /api/v1/treatment/{treatment_id}. Per-call lifecycle callbacks override the client defaults. */
    deleteById: (body: OzRequestOptions<operations["delete_treatment"]>) => ReturnType<ClientForPath<paths["/api/v1/treatment/{treatment_id}"], "application/json">["DELETE"]>;
    /** Calls GET /api/v1/treatment/{treatment_id}. Per-call lifecycle callbacks override the client defaults. */
    getById: (body: OzRequestOptions<operations["get_treatment"]>) => ReturnType<ClientForPath<paths["/api/v1/treatment/{treatment_id}"], "application/json">["GET"]>;
    /** Calls PATCH /api/v1/treatment/{treatment_id}. Per-call lifecycle callbacks override the client defaults. */
    updateTreatment: (body: OzRequestOptions<operations["update_treatment"]>) => ReturnType<ClientForPath<paths["/api/v1/treatment/{treatment_id}"], "application/json">["PATCH"]>;
    /** Calls GET /api/v1/treatment/{treatment_id}/notes. Per-call lifecycle callbacks override the client defaults. */
    getAllNotesInTreatment: (body: OzRequestOptions<operations["get_all_notes_in_treatment"]>) => ReturnType<ClientForPath<paths["/api/v1/treatment/{treatment_id}/notes"], "application/json">["GET"]>;
    /** Calls POST /api/v1/treatment/{treatment_id}/notes. Per-call lifecycle callbacks override the client defaults. */
    createNote: (body: OzRequestOptions<operations["create_note"]>) => ReturnType<ClientForPath<paths["/api/v1/treatment/{treatment_id}/notes"], "application/json">["POST"]>;
    /** Calls GET /api/v1/treatment/{treatment_id}/sessions. Per-call lifecycle callbacks override the client defaults. */
    getAllSessionByTreatment: (body: OzRequestOptions<operations["get_all_session_by_treatment"]>) => ReturnType<ClientForPath<paths["/api/v1/treatment/{treatment_id}/sessions"], "application/json">["GET"]>;
  };
  users: {
    /** Calls GET /api/v1/users. Per-call lifecycle callbacks override the client defaults. */
    getAllUsers: (body?: OzRequestOptions<operations["get_all_users"]>) => ReturnType<ClientForPath<paths["/api/v1/users"], "application/json">["GET"]>;
    /** Calls POST /api/v1/users. Per-call lifecycle callbacks override the client defaults. */
    createUser: (body: OzRequestOptions<operations["create_user"]>) => ReturnType<ClientForPath<paths["/api/v1/users"], "application/json">["POST"]>;
    /** Calls DELETE /api/v1/users/{user_id}. Per-call lifecycle callbacks override the client defaults. */
    deleteById: (body: OzRequestOptions<operations["delete_user"]>) => ReturnType<ClientForPath<paths["/api/v1/users/{user_id}"], "application/json">["DELETE"]>;
    /** Calls GET /api/v1/users/{user_id}. Per-call lifecycle callbacks override the client defaults. */
    getById: (body: OzRequestOptions<operations["get_user"]>) => ReturnType<ClientForPath<paths["/api/v1/users/{user_id}"], "application/json">["GET"]>;
  };
}

/** Creates a typed client with optional default request lifecycle callbacks. */
export function createOzClient(options: OzClientOptions): OzClient {
  const {
    onRequest,
    onResponse,
    onError,
    ...clientOptions
  } = options;
  const raw_client = createClient<paths>(clientOptions);
  const defaults = { onRequest, onResponse, onError };
  return {
    /** The underlying openapi-fetch client for direct path-based calls. */
    raw_client,
    appointment: {
      /** Calls GET /api/v1/appointment. Per-call lifecycle callbacks override the client defaults. */
      getAllAppointmentsInTimeRange: (body: OzRequestOptions<operations["get_all_appointments_in_time_range"]>) => raw_client.GET("/api/v1/appointment", withCallbacks(body, defaults)),
      /** Calls GET /api/v1/appointment/attending/{staff_id}. Per-call lifecycle callbacks override the client defaults. */
      getAllAppointmentsFromStaff: (body: OzRequestOptions<operations["get_all_appointments_from_staff"]>) => raw_client.GET("/api/v1/appointment/attending/{staff_id}", withCallbacks(body, defaults)),
      /** Calls GET /api/v1/appointment/creator/{staff_id}. Per-call lifecycle callbacks override the client defaults. */
      getAllAppointmentsFromCreator: (body: OzRequestOptions<operations["get_all_appointments_from_creator"]>) => raw_client.GET("/api/v1/appointment/creator/{staff_id}", withCallbacks(body, defaults)),
      /** Calls PATCH /api/v1/appointment/{appointment_id}. Per-call lifecycle callbacks override the client defaults. */
      updateAppointment: (body: OzRequestOptions<operations["update_appointment"]>) => raw_client.PATCH("/api/v1/appointment/{appointment_id}", withCallbacks(body, defaults)),
      },
    auth: {
      /** Calls POST /api/v1/auth/change-password. Per-call lifecycle callbacks override the client defaults. */
      changePassword: (body: OzRequestOptions<operations["changePassword"]>) => raw_client.POST("/api/v1/auth/change-password", withCallbacks(body, defaults)),
      /** Calls POST /api/v1/auth/forgot-password. Per-call lifecycle callbacks override the client defaults. */
      forgotPassword: (body: OzRequestOptions<operations["forgot_password"]>) => raw_client.POST("/api/v1/auth/forgot-password", withCallbacks(body, defaults)),
      /** Calls POST /api/v1/auth/login. Per-call lifecycle callbacks override the client defaults. */
      login: (body: OzRequestOptions<operations["login"]>) => raw_client.POST("/api/v1/auth/login", withCallbacks(body, defaults)),
      /** Calls POST /api/v1/auth/logout. Per-call lifecycle callbacks override the client defaults. */
      logout: (body?: OzRequestOptions<operations["logout"]>) => raw_client.POST("/api/v1/auth/logout", withCallbacks(body, defaults)),
      /** Calls GET /api/v1/auth/me. Per-call lifecycle callbacks override the client defaults. */
      me: (body?: OzRequestOptions<operations["me"]>) => raw_client.GET("/api/v1/auth/me", withCallbacks(body, defaults)),
      /** Calls GET /api/v1/auth/settings. Per-call lifecycle callbacks override the client defaults. */
      getUserSettings: (body?: OzRequestOptions<operations["get_user_settings"]>) => raw_client.GET("/api/v1/auth/settings", withCallbacks(body, defaults)),
      /** Calls PATCH /api/v1/auth/settings. Per-call lifecycle callbacks override the client defaults. */
      updateUserSettings: (body: OzRequestOptions<operations["update_user_settings"]>) => raw_client.PATCH("/api/v1/auth/settings", withCallbacks(body, defaults)),
      },
    clinic: {
      /** Calls GET /api/v1/clinic. Per-call lifecycle callbacks override the client defaults. */
      getAllClinics: (body?: OzRequestOptions<operations["get_all_clinics"]>) => raw_client.GET("/api/v1/clinic", withCallbacks(body, defaults)),
      /** Calls POST /api/v1/clinic. Per-call lifecycle callbacks override the client defaults. */
      createClinic: (body: OzRequestOptions<operations["create_clinic"]>) => raw_client.POST("/api/v1/clinic", withCallbacks(body, defaults)),
      },
    clinic_service: {
      /** Calls GET /api/v1/clinic_service. Per-call lifecycle callbacks override the client defaults. */
      getAllClinicServices: (body?: OzRequestOptions<operations["get_all_clinic_services"]>) => raw_client.GET("/api/v1/clinic_service", withCallbacks(body, defaults)),
      /** Calls POST /api/v1/clinic_service. Per-call lifecycle callbacks override the client defaults. */
      createClinicService: (body: OzRequestOptions<operations["create_clinic_service"]>) => raw_client.POST("/api/v1/clinic_service", withCallbacks(body, defaults)),
      /** Calls DELETE /api/v1/clinic_service/{service_id}. Per-call lifecycle callbacks override the client defaults. */
      deleteClinicService: (body: OzRequestOptions<operations["delete_clinic_service"]>) => raw_client.DELETE("/api/v1/clinic_service/{service_id}", withCallbacks(body, defaults)),
      /** Calls GET /api/v1/clinic_service/{service_id}. Per-call lifecycle callbacks override the client defaults. */
      getClinicService: (body: OzRequestOptions<operations["get_clinic_service"]>) => raw_client.GET("/api/v1/clinic_service/{service_id}", withCallbacks(body, defaults)),
      /** Calls PATCH /api/v1/clinic_service/{service_id}. Per-call lifecycle callbacks override the client defaults. */
      updateClinicService: (body: OzRequestOptions<operations["update_clinic_service"]>) => raw_client.PATCH("/api/v1/clinic_service/{service_id}", withCallbacks(body, defaults)),
      },
    note: {
      /** Calls DELETE /api/v1/note/{note_id}. Per-call lifecycle callbacks override the client defaults. */
      deleteById: (body: OzRequestOptions<operations["delete_note"]>) => raw_client.DELETE("/api/v1/note/{note_id}", withCallbacks(body, defaults)),
      /** Calls GET /api/v1/note/{note_id}. Per-call lifecycle callbacks override the client defaults. */
      getById: (body: OzRequestOptions<operations["get_note"]>) => raw_client.GET("/api/v1/note/{note_id}", withCallbacks(body, defaults)),
      /** Calls PATCH /api/v1/note/{note_id}. Per-call lifecycle callbacks override the client defaults. */
      updateNote: (body: OzRequestOptions<operations["update_note"]>) => raw_client.PATCH("/api/v1/note/{note_id}", withCallbacks(body, defaults)),
      },
    obra: {
      /** Calls GET /api/v1/obra. Per-call lifecycle callbacks override the client defaults. */
      getAllObrasSociales: (body?: OzRequestOptions<operations["get_all_obras_sociales"]>) => raw_client.GET("/api/v1/obra", withCallbacks(body, defaults)),
      /** Calls POST /api/v1/obra. Per-call lifecycle callbacks override the client defaults. */
      createObraSocial: (body: OzRequestOptions<operations["create_obra_social"]>) => raw_client.POST("/api/v1/obra", withCallbacks(body, defaults)),
      /** Calls GET /api/v1/obra/{name}. Per-call lifecycle callbacks override the client defaults. */
      getObraSocial: (body: OzRequestOptions<operations["get_obra_social"]>) => raw_client.GET("/api/v1/obra/{name}", withCallbacks(body, defaults)),
      /** Calls PATCH /api/v1/obra/{name}. Per-call lifecycle callbacks override the client defaults. */
      updateObraSocial: (body: OzRequestOptions<operations["update_obra_social"]>) => raw_client.PATCH("/api/v1/obra/{name}", withCallbacks(body, defaults)),
      },
    patient: {
      /** Calls GET /api/v1/patient. Per-call lifecycle callbacks override the client defaults. */
      getAllPatients: (body?: OzRequestOptions<operations["get_all_patients"]>) => raw_client.GET("/api/v1/patient", withCallbacks(body, defaults)),
      /** Calls POST /api/v1/patient. Per-call lifecycle callbacks override the client defaults. */
      createPatient: (body: OzRequestOptions<operations["create_patient"]>) => raw_client.POST("/api/v1/patient", withCallbacks(body, defaults)),
      /** Calls GET /api/v1/patient/{patient_id}. Per-call lifecycle callbacks override the client defaults. */
      getById: (body: OzRequestOptions<operations["get_patient"]>) => raw_client.GET("/api/v1/patient/{patient_id}", withCallbacks(body, defaults)),
      /** Calls PATCH /api/v1/patient/{patient_id}. Per-call lifecycle callbacks override the client defaults. */
      updatePatient: (body: OzRequestOptions<operations["update_patient"]>) => raw_client.PATCH("/api/v1/patient/{patient_id}", withCallbacks(body, defaults)),
      /** Calls GET /api/v1/patient/{patient_id}/clinical-history. Per-call lifecycle callbacks override the client defaults. */
      buildClinicHistory: (body: OzRequestOptions<operations["build_clinic_history"]>) => raw_client.GET("/api/v1/patient/{patient_id}/clinical-history", withCallbacks(body, defaults)),
      /** Calls PATCH /api/v1/patient/{patient_id}/discharge. Per-call lifecycle callbacks override the client defaults. */
      dischargePatient: (body: OzRequestOptions<operations["discharge_patient"]>) => raw_client.PATCH("/api/v1/patient/{patient_id}/discharge", withCallbacks(body, defaults)),
      },
    payment: {
      /** Calls GET /api/v1/payment. Per-call lifecycle callbacks override the client defaults. */
      getAllPayments: (body?: OzRequestOptions<operations["get_all_payments"]>) => raw_client.GET("/api/v1/payment", withCallbacks(body, defaults)),
      /** Calls POST /api/v1/payment. Per-call lifecycle callbacks override the client defaults. */
      registerPayment: (body: OzRequestOptions<operations["register_payment"]>) => raw_client.POST("/api/v1/payment", withCallbacks(body, defaults)),
      /** Calls GET /api/v1/payment/by-payer/{payer_id}. Per-call lifecycle callbacks override the client defaults. */
      getAllPaymentsFromId: (body: OzRequestOptions<operations["get_all_payments_from_id"]>) => raw_client.GET("/api/v1/payment/by-payer/{payer_id}", withCallbacks(body, defaults)),
      /** Calls DELETE /api/v1/payment/{payment_id}. Per-call lifecycle callbacks override the client defaults. */
      deleteById: (body: OzRequestOptions<operations["delete_payment"]>) => raw_client.DELETE("/api/v1/payment/{payment_id}", withCallbacks(body, defaults)),
      /** Calls GET /api/v1/payment/{payment_id}. Per-call lifecycle callbacks override the client defaults. */
      getById: (body: OzRequestOptions<operations["get_payment"]>) => raw_client.GET("/api/v1/payment/{payment_id}", withCallbacks(body, defaults)),
      /** Calls PATCH /api/v1/payment/{payment_id}. Per-call lifecycle callbacks override the client defaults. */
      updatePayment: (body: OzRequestOptions<operations["update_payment"]>) => raw_client.PATCH("/api/v1/payment/{payment_id}", withCallbacks(body, defaults)),
      },
    session: {
      /** Calls POST /api/v1/session. Per-call lifecycle callbacks override the client defaults. */
      createSession: (body: OzRequestOptions<operations["create_session"]>) => raw_client.POST("/api/v1/session", withCallbacks(body, defaults)),
      /** Calls GET /api/v1/session/{session_id}. Per-call lifecycle callbacks override the client defaults. */
      getById: (body: OzRequestOptions<operations["get_session"]>) => raw_client.GET("/api/v1/session/{session_id}", withCallbacks(body, defaults)),
      /** Calls PATCH /api/v1/session/{session_id}. Per-call lifecycle callbacks override the client defaults. */
      updateSession: (body: OzRequestOptions<operations["update_session"]>) => raw_client.PATCH("/api/v1/session/{session_id}", withCallbacks(body, defaults)),
      },
    sessions: {
      /** Calls POST /api/v1/sessions/{session_id}/appointment. Per-call lifecycle callbacks override the client defaults. */
      createAppointment: (body: OzRequestOptions<operations["create_appointment"]>) => raw_client.POST("/api/v1/sessions/{session_id}/appointment", withCallbacks(body, defaults)),
      },
    staff: {
      /** Calls GET /api/v1/staff. Per-call lifecycle callbacks override the client defaults. */
      getAllStaff: (body?: OzRequestOptions<operations["get_all_staff"]>) => raw_client.GET("/api/v1/staff", withCallbacks(body, defaults)),
      /** Calls GET /api/v1/staff/{staff_id}. Per-call lifecycle callbacks override the client defaults. */
      getById: (body: OzRequestOptions<operations["get_staff"]>) => raw_client.GET("/api/v1/staff/{staff_id}", withCallbacks(body, defaults)),
      /** Calls PATCH /api/v1/staff/{staff_id}. Per-call lifecycle callbacks override the client defaults. */
      updateStaff: (body: OzRequestOptions<operations["update_staff"]>) => raw_client.PATCH("/api/v1/staff/{staff_id}", withCallbacks(body, defaults)),
      },
    treatment: {
      /** Calls POST /api/v1/treatment. Per-call lifecycle callbacks override the client defaults. */
      createTreatment: (body: OzRequestOptions<operations["create_treatment"]>) => raw_client.POST("/api/v1/treatment", withCallbacks(body, defaults)),
      /** Calls GET /api/v1/treatment/patient/{patient_id}. Per-call lifecycle callbacks override the client defaults. */
      getAllTreatmentsFromPatient: (body: OzRequestOptions<operations["get_all_treatments_from_patient"]>) => raw_client.GET("/api/v1/treatment/patient/{patient_id}", withCallbacks(body, defaults)),
      /** Calls GET /api/v1/treatment/staff/{staff_id}. Per-call lifecycle callbacks override the client defaults. */
      getAllTreatmentsFromStaff: (body: OzRequestOptions<operations["get_all_treatments_from_staff"]>) => raw_client.GET("/api/v1/treatment/staff/{staff_id}", withCallbacks(body, defaults)),
      /** Calls DELETE /api/v1/treatment/{treatment_id}. Per-call lifecycle callbacks override the client defaults. */
      deleteById: (body: OzRequestOptions<operations["delete_treatment"]>) => raw_client.DELETE("/api/v1/treatment/{treatment_id}", withCallbacks(body, defaults)),
      /** Calls GET /api/v1/treatment/{treatment_id}. Per-call lifecycle callbacks override the client defaults. */
      getById: (body: OzRequestOptions<operations["get_treatment"]>) => raw_client.GET("/api/v1/treatment/{treatment_id}", withCallbacks(body, defaults)),
      /** Calls PATCH /api/v1/treatment/{treatment_id}. Per-call lifecycle callbacks override the client defaults. */
      updateTreatment: (body: OzRequestOptions<operations["update_treatment"]>) => raw_client.PATCH("/api/v1/treatment/{treatment_id}", withCallbacks(body, defaults)),
      /** Calls GET /api/v1/treatment/{treatment_id}/notes. Per-call lifecycle callbacks override the client defaults. */
      getAllNotesInTreatment: (body: OzRequestOptions<operations["get_all_notes_in_treatment"]>) => raw_client.GET("/api/v1/treatment/{treatment_id}/notes", withCallbacks(body, defaults)),
      /** Calls POST /api/v1/treatment/{treatment_id}/notes. Per-call lifecycle callbacks override the client defaults. */
      createNote: (body: OzRequestOptions<operations["create_note"]>) => raw_client.POST("/api/v1/treatment/{treatment_id}/notes", withCallbacks(body, defaults)),
      /** Calls GET /api/v1/treatment/{treatment_id}/sessions. Per-call lifecycle callbacks override the client defaults. */
      getAllSessionByTreatment: (body: OzRequestOptions<operations["get_all_session_by_treatment"]>) => raw_client.GET("/api/v1/treatment/{treatment_id}/sessions", withCallbacks(body, defaults)),
      },
    users: {
      /** Calls GET /api/v1/users. Per-call lifecycle callbacks override the client defaults. */
      getAllUsers: (body?: OzRequestOptions<operations["get_all_users"]>) => raw_client.GET("/api/v1/users", withCallbacks(body, defaults)),
      /** Calls POST /api/v1/users. Per-call lifecycle callbacks override the client defaults. */
      createUser: (body: OzRequestOptions<operations["create_user"]>) => raw_client.POST("/api/v1/users", withCallbacks(body, defaults)),
      /** Calls DELETE /api/v1/users/{user_id}. Per-call lifecycle callbacks override the client defaults. */
      deleteById: (body: OzRequestOptions<operations["delete_user"]>) => raw_client.DELETE("/api/v1/users/{user_id}", withCallbacks(body, defaults)),
      /** Calls GET /api/v1/users/{user_id}. Per-call lifecycle callbacks override the client defaults. */
      getById: (body: OzRequestOptions<operations["get_user"]>) => raw_client.GET("/api/v1/users/{user_id}", withCallbacks(body, defaults)),
      },
  };
}
